### ISSUE TITLE
Upgrade react-native-gesture-handler 2

### ISSUE THREAD

**Issue by codingdais** [jamsch/react-native-duo-drag-drop#2]
First I would like to say thanks... will you upgrade react-native-gesture-handler 2 and it's not working 0.68.2.... thanks

**Comment by jamsch** [comment]
Working on a beta update that will come out soon and will support `react-native-gesture-handler@^2.2.1`, `react-native-reanimated@^2.8.0` & `react-native@^0.68.2`.

**Comment by jamsch** [comment]
Just released a major version that includes react-native-gesture-handler v2, https://github.com/jamsch/react-native-duo-drag-drop/releases/tag/v1.0.0

**Comment by codingdais** [comment]
Thank you so much it's working fine..
