### ISSUE TITLE
Gestures not working on words

### ISSUE THREAD

**Issue by Daarrik** [jamsch/react-native-duo-drag-drop#4]
![notworking](https://user-images.githubusercontent.com/77186596/205777949-5462b9cf-7d86-4727-b45b-2e306076af9b.gif)

Not sure what could be causing this for me, but the elements generated from the words don't seem to have any functionality. Currently on react-native-gesture-handler ^2.8.0 and react-native-reanimated ^2.13.0
Edit: also on react-native 0.70.5

**Comment by jamsch** [comment]
In the past I've had a few intermittent issues like that before on app launches. Problem seems to be the whole UI thread freezing to any responses (for some unknown reason, likely something upstream with gesture-handler/reanimated) -- I recall even pressing buttons wouldn't work.

I can't seem to reproduce this when running Expo 47 (react-native 0.70.5)

<img width="1048" alt="Screenshot 2022-12-06 at 3 50 37 PM" src="https://user-images.githubusercontent.com/12927717/205797416-360109b0-aafc-49de-9a73-38a0575cd6df.png">

To reproduce what I'm seeing:

```sh
git clone git@github.com:jamsch/react-native-duo-drag-drop.git
cd react-native-duo-drag-drop
npm install

# Build react-native-duo-drag-drop
npm run prepare

# Run on android
cd example
npm run android
```

One thing I noticed is that the buttons seem greyed out. Are you able to share a code sample of your project?

**Comment by Daarrik** [comment]
I pushed the entire project in this branch [here](https://github.com/Daarrik/benkyo/tree/drag-and-drop). The screen for the gif in the initial post is under "Random."

I'm new to React Native, so I should also mention that I have not been using Expo and have been using `npx react-native start` and `npx react-native run-android` for the project. I'm not sure if this could have been the cause for the issue.

**Comment by jamsch** [comment]
@Daarrik There's a few things:

- You need to place GestureHandlerRootView at the root of the app

```js
const App = () => {
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <NavigationContainer>
      ....
     </NavigationContainer>
   </GestureHandlerRootView>
);
```

In `GameTest.js` you need to add a `flex: 1` to the root View

```js
  return (
    <View style={{ flex: 1 }}>
      <DragAndDrop reading={reading} />
    </View>
  );
```

To fix style height/alignment issues for the Drag and Drop with the button, wrap it in a ScrollView

```js
const DragAndDrop = ({ reading }) => {
  const ref = useRef(null);

  return (
    <ScrollView style={{ margin: 20, flex: 1 }}>
      <DuoDragDrop
        ref={ref}
        words={['test', 'testtest', 'te', 't']}
        // gesturesDisabled={false}
      />
      <Button
        title="get words"
        onPress={() => {
          console.log(ref.current.getWords());
        }}
      />
    </ScrollView>
  );
};
```

**Comment by Daarrik** [comment]
Those changes worked on my end! Thank you so much for the help and sharing this repo.
