### ISSUE TITLE
What is the best way to reset this on a press of a button

### ISSUE THREAD

**Issue by Pau1fitz** [jamsch/react-native-duo-drag-drop#5]
Title is pretty self-explantory. Not very clear from the docs how you would reset the guesses on press of reset button

**Comment by jamsch** [comment]
Hey @Pau1fitz, depending on your needs you could use either one of the following: 

- Using `key={...}` prop to re-mount the drag-and-drop with your new set of words:

https://github.com/user-attachments/assets/e36743fc-1ef9-478e-b89e-dcd54e8ce5e2

- Using the `extraData` prop to re-render the word elements when a stateful value changes (such as your word gradings)

https://github.com/user-attachments/assets/839d74e5-0e7d-4470-9af9-f64ac9ee692a

- Calling `setOffsets` from the ref, e.g. `duoDragDropRef.current?.setOffsets(Array(wordsList.length).fill(-1));` which will animate the words back to the bank.

https://github.com/user-attachments/assets/c947a373-54e1-4650-8d15-b01f2556eaf9

By the way, It seems though `setOffsets()` was broken with the latest version of reanimated, so I've just released v1.1.3 to fix this.

**Comment by Pau1fitz** [comment]
nice, just updated to v 1.1.3 and it works well. Great work
